{
 "title": "Mistral Overview",
 "description": "Mistral dashboard to display metrics from Prometheus",
 "tags": [ "mistral" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "inter", "label": "Sampling", "query": "2m,3m,4m,5m,10m" },
   {
    "name": "mistral_namespace",
    "label": "Project",
    "query": "label_values(mistral_cluster, namespace)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mistral_cluster, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mistral Cluster Status",
   "type": "stat",
   "description": "Mistral cluster status (Up, Degraded, Down)",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(topk(1, mistral_cluster{namespace=\"$mistral_namespace\", cluster=\"$cluster\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"state\") FROM \"mistral_cluster\" WHERE (\"namespace\" ='$project' ) AND time >= now() - 2m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Completion speed per sec",
   "type": "timeseries",
   "description": "Displays number of completed workflows, tasks and actions per second",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "tasks",
     "expr": "max(topk(1, delta(mistral_workflow_count{namespace=\"$mistral_namespace\", cluster=\"$cluster\",state=\"SUCCESS\"}[$inter])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Workflow",
     "measurement": "mistral_entities",
     "query": "SELECT difference(last(\"tasks_success\")) FROM \"mistral_entities\" WHERE (\"namespace\" ='$project') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "tasks_success" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "tenant", "operator": "=~", "value": "/^$tenant/" }
     ]
    },
    {
     "alias": "workflows",
     "expr": "max(topk(1, delta(mistral_task_count{namespace=\"$mistral_namespace\", cluster=\"$cluster\",state=\"SUCCESS\"}[$inter])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Task",
     "measurement": "mistral_entities",
     "query": "SELECT difference(last(\"workflows_success\")) FROM \"mistral_entities\" WHERE (\"namespace\" ='$project') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "workflows_success" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "tenant", "operator": "=~", "value": "/^$tenant$/" }
     ]
    },
    {
     "alias": "actions",
     "expr": "max(topk(1, delta(mistral_action_count{namespace=\"$mistral_namespace\", cluster=\"$cluster\",state=\"SUCCESS\"}[$inter])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Action",
     "measurement": "mistral_entities",
     "query": "SELECT difference(last(\"actions_success\")) FROM \"mistral_entities\" WHERE (\"namespace\" ='$project') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "actions_success" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "tenant", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "MEM Usage Summary",
   "type": "timeseries",
   "description": "Displays amount of memory requested by Mistral pods, memory usage and limit",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "usage: $tag_pod_name",
     "expr": "max(container_memory_usage_bytes{container!=\"POD\",image!=\"\",namespace=\"$mistral_namespace\", cluster=\"$cluster\",container=~\"mistral.+\"}) by (container)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Max {{container}}",
     "measurement": "memory/usage",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^(mistral-api|mistral-executor|mistral-engine|mistral-event-engine|mistral-notifier|mistral-monitoring|monitoring-agent)/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      {
       "condition": "AND",
       "key": "pod_name",
       "operator": "=~",
       "value": "/^(mistral-api|mistral-executor|mistral-engine|mistral-event-engine|mistral-notifier|mistral-monitoring|monitoring-agent)/"
      }
     ]
    },
    {
     "alias": "limit: $tag_pod_name",
     "expr": "avg(container_memory_usage_bytes{container!=\"POD\",image!=\"\",namespace=\"$mistral_namespace\", cluster=\"$cluster\",container=~\"mistral.+\"}) by (container)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Avg {{container}}",
     "measurement": "memory/limit",
     "query": "SELECT mean(\"value\") FROM \"memory/limit\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^(mistral-api|mistral-executor|mistral-engine|mistral-event-engine|mistral-notifier|mistral-monitoring|monitoring-agent)/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      {
       "condition": "AND",
       "key": "pod_name",
       "operator": "=~",
       "value": "/^(mistral-api|mistral-executor|mistral-engine|mistral-event-engine|mistral-notifier|mistral-monitoring|monitoring-agent)/"
      }
     ]
    },
    {
     "alias": "request: $tag_pod_name",
     "expr": "min(container_memory_usage_bytes{container!=\"POD\",image!=\"\",namespace=\"$mistral_namespace\", cluster=\"$cluster\",container=~\"mistral.+\"}) by (container)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Min {{container}}",
     "measurement": "memory/request",
     "query": "SELECT mean(\"value\") FROM \"memory/request\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^(mistral-api|mistral-executor|mistral-engine|mistral-event-engine|mistral-notifier|mistral-monitoring|monitoring-agent)/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      {
       "condition": "AND",
       "key": "pod_name",
       "operator": "=~",
       "value": "/^(mistral-api|mistral-executor|mistral-engine|mistral-event-engine|mistral-notifier|mistral-monitoring|monitoring-agent)/"
      }
     ]
    }
   ]
  },
  {
   "title": "Mistral Opensource version",
   "type": "stat",
   "description": "Version of using opensource Mistral",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mistral_version{namespace=\"$mistral_namespace\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"state\") FROM \"mistral_cluster\" WHERE (\"namespace\" ='$project' ) AND time >= now() - 2m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Maintenance status",
   "type": "stat",
   "description": "Displays Mistral Maintenance mode status",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(topk(1, mistral_maintenance_status{namespace=\"$mistral_namespace\", cluster=\"$cluster\"}))",
     "measurement": "mistral_maintenance",
     "query": "SELECT last(\"status\") FROM \"mistral_maintenance\" WHERE (\"namespace\" ='$project' ) AND time >= now() - 2m",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Tasks in non-terminal state",
   "type": "timeseries",
   "description": "Displays number of tasks in non-terminal state",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Tasks in non-terminal state",
     "expr": "max(topk(1, mistral_task_count{namespace=\"$mistral_namespace\", cluster=\"$cluster\",state=~\"RUNNING|WAITING\"}) by (state)) by (state)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tenant" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "measurement": "mistral_entities",
     "query": "SELECT mean(\"tasks_running\") + mean(\"tasks_waiting\") FROM \"mistral_entities\" WHERE (\"namespace\" ='$project') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "task_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "tasks_waiting" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "tenant", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage Summary",
   "type": "timeseries",
   "description": "Displays amount of millicores requested by Mistral pods, millicores usage and limit",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "usage: $tag_pod_name",
     "expr": "max(rate(container_cpu_user_seconds_total{container!=\"POD\",image!=\"\",namespace=\"$mistral_namespace\", cluster=\"$cluster\",container=~\"mistral.+\"}[$inter])) by (container)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Max {{ container}}",
     "measurement": "cpu/usage_rate",
     "query": "SELECT mean(\"value\") FROM \"cpu/usage_rate\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^(mistral-api|mistral-executor|mistral-engine|mistral-event-engine|mistral-notifier|mistral-monitoring|monitoring-agent)/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      {
       "condition": "AND",
       "key": "pod_name",
       "operator": "=~",
       "value": "/^(mistral-api|mistral-executor|mistral-engine|mistral-event-engine|mistral-notifier|mistral-monitoring|monitoring-agent)/"
      }
     ]
    },
    {
     "alias": "limit: $tag_pod_name",
     "expr": "avg(rate(container_cpu_user_seconds_total{container!=\"POD\",image!=\"\",namespace=\"$mistral_namespace\", cluster=\"$cluster\",container=~\"mistral.+\"}[$inter])) by (container)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Avg {{ container}}",
     "measurement": "cpu/limit",
     "query": "SELECT mean(\"value\") FROM \"cpu/limit\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^(mistral-api|mistral-executor|mistral-engine|mistral-event-engine|mistral-notifier|mistral-monitoring|monitoring-agent)/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      {
       "condition": "AND",
       "key": "pod_name",
       "operator": "=~",
       "value": "/^(mistral-api|mistral-executor|mistral-engine|mistral-event-engine|mistral-notifier|mistral-monitoring|monitoring-agent)/"
      }
     ]
    },
    {
     "alias": "request: $tag_pod_name",
     "expr": "min(rate(container_cpu_user_seconds_total{container!=\"POD\",image!=\"\",namespace=\"$mistral_namespace\", cluster=\"$cluster\",container=~\"mistral.+\"}[$inter])) by (container)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Min {{ container}}",
     "measurement": "cpu/request",
     "query": "SELECT mean(\"value\") FROM \"cpu/request\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project' AND \"pod_name\" =~ /^(mistral-api|mistral-executor|mistral-engine|mistral-event-engine|mistral-notifier|mistral-monitoring|monitoring-agent)/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      {
       "condition": "AND",
       "key": "pod_name",
       "operator": "=~",
       "value": "/^(mistral-api|mistral-executor|mistral-engine|mistral-event-engine|mistral-notifier|mistral-monitoring|monitoring-agent)/"
      }
     ]
    }
   ]
  },
  {
   "title": "Mistral E2E Smoke",
   "type": "stat",
   "description": "Displays Mistral E2E smoke test status",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(topk(1, mistral_smoke_status{namespace=\"$mistral_namespace\", cluster=\"$cluster\"}))",
     "measurement": "mistral_entities",
     "query": "SELECT last(\"smoke\") FROM \"mistral_maintenance\" WHERE (\"namespace\" ='$project') AND time >= now() - 2m",
     "select": [
      [
       { "params": [ "smoke" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "tenant", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral Apps Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mistral API Status",
   "type": "stat",
   "description": "Mistral API status (Up, Degraded, Down)",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(topk(1, mistral_state{namespace=\"$mistral_namespace\", cluster=\"$cluster\",name='mistral-api'}))",
     "measurement": "mistral_apps",
     "query": "SELECT last(\"state\") FROM \"mistral_apps\" WHERE (\"namespace\" ='$project'  AND \"name\" =~ /^mistral-api/) AND time >= now() - 2m ",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^mistral-api/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral Executor Status",
   "type": "stat",
   "description": "Mistral executor status (Up, Degraded, Down)",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(topk(1, mistral_state{namespace=\"$mistral_namespace\", cluster=\"$cluster\",name='mistral-executor'}))",
     "measurement": "mistral_apps",
     "query": "SELECT last(\"state\") FROM \"mistral_apps\" WHERE (\"namespace\" ='$project'  AND \"name\" =~ /^mistral-executor/) AND time >= now() - 2m ",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^mistral-executor/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral Engine Status",
   "type": "stat",
   "description": "Mistral engine status (Up, Degraded, Down)",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(topk(1, mistral_state{namespace=\"$mistral_namespace\", cluster=\"$cluster\",name='mistral-engine'}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"state\") FROM \"mistral_apps\" WHERE (\"namespace\" ='$project'  AND \"name\" =~ /^mistral-engine/) AND time >= now() - 2m ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mistral Notifier Status",
   "type": "stat",
   "description": "Mistral notifier status (Up, Degraded, Down)",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(topk(1, mistral_state{namespace=\"$mistral_namespace\", cluster=\"$cluster\",name='mistral-notifier'}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"state\") FROM \"mistral_apps\" WHERE (\"namespace\" ='$project'  AND \"name\" =~ /^mistral-notifier/) AND time >= now() - 2m ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mistral Monitoring Status",
   "type": "stat",
   "description": "Mistral monitoring status (Up, Degraded, Down)",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(topk(1, mistral_state{namespace=\"$mistral_namespace\", cluster=\"$cluster\",name='mistral-monitoring'}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"state\") FROM \"mistral_apps\" WHERE (\"namespace\" ='$project'  AND \"name\" =~ /^mistral-monitoring/) AND time >= now() - 2m ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mistral API pods",
   "type": "stat",
   "description": "Displays current number of available Mistral API pods.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(topk(1, mistral_available_replicas{namespace=\"$mistral_namespace\", cluster=\"$cluster\",name=\"mistral-api\"}))",
     "measurement": "mistral_apps",
     "query": "SELECT last(\"available_replicas\") FROM \"mistral_apps\" WHERE (\"name\" =~ /^mistral-api/ AND \"namespace\" ='$project' ) AND time >= now() - 2m",
     "select": [
      [
       { "params": [ "available_replicas" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^mistral-api/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral Executor pods",
   "type": "stat",
   "description": "Displays current number of available Mistral Executor pods.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(topk(1, mistral_available_replicas{namespace=\"$mistral_namespace\", cluster=\"$cluster\", name=\"mistral-executor\"}))",
     "measurement": "mistral_apps",
     "query": "SELECT last(\"available_replicas\") FROM \"mistral_apps\" WHERE (\"name\" =~ /^mistral-executor/ AND \"namespace\" ='$project' ) AND time >= now() - 2m",
     "select": [
      [
       { "params": [ "available_replicas" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^mistral-executor/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral Engine pods",
   "type": "stat",
   "description": "Displays current number of available Mistral Engine pods.",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(topk(1, mistral_available_replicas{namespace=\"$mistral_namespace\", cluster=\"$cluster\", name=\"mistral-engine\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mistral_apps",
     "query": "SELECT last(\"available_replicas\") FROM \"mistral_apps\" WHERE (\"name\" =~ /^mistral-engine/ AND \"namespace\" ='$project' ) AND time >= now() - 2m",
     "select": [
      [
       { "params": [ "available_replicas" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^mistral-engine/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral Notifier pods",
   "type": "stat",
   "description": "Displays current number of available Mistral Notifier pods.",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(topk(1, mistral_available_replicas{namespace=\"$mistral_namespace\", cluster=\"$cluster\", name=\"mistral-notifier\"}))",
     "measurement": "mistral_apps",
     "query": "SELECT last(\"available_replicas\") FROM \"mistral_apps\" WHERE (\"name\" =~ /^mistral-notifier/ AND \"namespace\" ='$project' ) AND time >= now() - 2m",
     "select": [
      [
       { "params": [ "available_replicas" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^mistral-notifier/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral Monitoring pods",
   "type": "stat",
   "description": "Displays current number of available Mistral Monitoring pods.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(topk(1, mistral_available_replicas{namespace=\"$mistral_namespace\", cluster=\"$cluster\", name=\"mistral-monitoring\"}))",
     "measurement": "mistral_apps",
     "query": "SELECT last(\"available_replicas\") FROM \"mistral_apps\" WHERE (\"name\" =~ /^mistral-monitoring/ AND \"namespace\" ='$project' ) AND time >= now() - 2m",
     "select": [
      [
       { "params": [ "available_replicas" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^mistral-monitoring/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Mistral Entities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workflow count by state",
   "type": "timeseries",
   "description": "Displays workflows count by state",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "running",
     "expr": "sum(topk(1, mistral_workflow_count{namespace=\"$mistral_namespace\", cluster=\"$cluster\"}) by (state))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Sum",
     "measurement": "mistral_entities",
     "query": "SELECT last(\"workflows_running\") FROM \"mistral_entities\" WHERE (\"namespace\" ='$project') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "workflows_running" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "tenant", "operator": "=~", "value": "/^$tenant$/" }
     ]
    },
    {
     "expr": "max(topk(1, mistral_workflow_count{namespace=\"$mistral_namespace\", cluster=\"$cluster\"}) by (state)) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Task count by state",
   "type": "timeseries",
   "description": "Displays tasks count by state",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "running",
     "expr": "sum(topk(1, mistral_task_count{namespace=\"$mistral_namespace\", cluster=\"$cluster\"}) by (state))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Sum",
     "measurement": "mistral_entities",
     "query": "SELECT last(\"tasks_running\") FROM \"mistral_entities\" WHERE (\"namespace\" ='$project') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "tasks_running" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "tenant", "operator": "=~", "value": "/^$tenant$/" }
     ]
    },
    {
     "expr": "max(topk(1, mistral_task_count{namespace=\"$mistral_namespace\", cluster=\"$cluster\"}) by (state)) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Delayed calls count by target",
   "type": "timeseries",
   "description": "Displays delayed calls count by target",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "complete_task",
     "expr": "sum(topk(1, mistral_delayed_calls_count{namespace=\"$mistral_namespace\", cluster=\"$cluster\"}) by (target))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Sum",
     "measurement": "mistral_entities",
     "query": "SELECT last(\"delayed_calls_mistral.engine.policies._complete_task\") FROM \"mistral_entities\" WHERE (\"namespace\" ='$project') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       {
        "params": [
         "delayed_calls_mistral.engine.policies._complete_task"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "tenant", "operator": "=~", "value": "/^$tenant$/" }
     ]
    },
    {
     "alias": "resume_executions",
     "expr": "max(topk(1, mistral_delayed_calls_count{namespace=\"$mistral_namespace\", cluster=\"$cluster\"}) by (target)) by (target)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{target}}",
     "measurement": "mistral_entities",
     "query": "SELECT last(\"delayed_calls_mistral.services.maintenance._resume_executions\") FROM \"mistral_entities\" WHERE (\"namespace\"='$project') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       {
        "params": [
         "delayed_calls_mistral.services.maintenance._resume_executions"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "tenant", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Action count by state",
   "type": "timeseries",
   "description": "Displays actions count by state",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "running",
     "expr": "sum(topk(1, mistral_action_count{namespace=\"$mistral_namespace\", cluster=\"$cluster\"}) by (state))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Sum",
     "measurement": "mistral_entities",
     "query": "SELECT last(\"actions_running\") FROM \"mistral_entities\" WHERE (\"namespace\" ='$project') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "actions_running" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "tenant", "operator": "=~", "value": "/^$tenant$/" }
     ]
    },
    {
     "alias": "success",
     "expr": "max(topk(1, mistral_action_count{namespace=\"$mistral_namespace\", cluster=\"$cluster\"}) by (state)) by (state)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "measurement": "mistral_entities",
     "query": "SELECT last(\"actions_success\") FROM \"mistral_entities\" WHERE (\"namespace\" ='$project') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "actions_success" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "tenant", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mistral Engine CPU Usage",
   "type": "timeseries",
   "description": "Displays Mistral Engine CPU usage (in millicores),  CPU limit and CPU requested for each engine pod",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "usage: $tag_pod_name",
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$mistral_namespace\", cluster=\"$cluster\",pod=~\"mistral-engine.+\"}[$inter])) by (pod)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "usage: {{pod}}",
     "measurement": "cpu/usage_rate",
     "query": "SELECT mean(\"value\") FROM \"cpu/usage_rate\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project' AND \"pod_name\" =~ /^mistral-engine/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-engine/" }
     ]
    },
    {
     "alias": "limit: $tag_pod_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu/limit",
     "query": "SELECT mean(\"value\") FROM \"cpu/limit\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^mistral-engine/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-engine/" }
     ]
    },
    {
     "alias": "request: $tag_pod_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu/request",
     "query": "SELECT mean(\"value\") FROM \"cpu/request\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^mistral-engine/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-engine/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral API CPU Usage",
   "type": "timeseries",
   "description": "Displays Mistral API CPU usage (in millicores),  CPU limit and CPU requested for each API pod",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "usage: $tag_pod_name",
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$mistral_namespace\", cluster=\"$cluster\",pod=~\"mistral-api.+\"}[$inter])) by (pod)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "measurement": "cpu/usage_rate",
     "query": "SELECT mean(\"value\") FROM \"cpu/usage_rate\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\"='$project'  AND \"pod_name\" =~ /^mistral-api/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-api/" }
     ]
    },
    {
     "alias": "limit: $tag_pod_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu/limit",
     "query": "SELECT mean(\"value\") FROM \"cpu/limit\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^mistral-api/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-api/" }
     ]
    },
    {
     "alias": "request: $tag_pod_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu/request",
     "query": "SELECT mean(\"value\") FROM \"cpu/request\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\"='$project'  AND \"pod_name\" =~ /^mistral-api/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-api/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral Executor CPU Usage",
   "type": "timeseries",
   "description": "Displays Mistral Executor CPU usage (in millicores),  CPU limit and CPU requested for each Executor pod",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "usage: $tag_pod_name",
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$mistral_namespace\", cluster=\"$cluster\",pod=~\"mistral-executor.+\"}[$inter])) by (pod)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "measurement": "cpu/usage_rate",
     "query": "SELECT mean(\"value\") FROM \"cpu/usage_rate\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^mistral-executor/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-executor/" }
     ]
    },
    {
     "alias": "limit: $tag_pod_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu/limit",
     "query": "SELECT mean(\"value\") FROM \"cpu/limit\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^mistral-executor/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-executor/" }
     ]
    },
    {
     "alias": "request: $tag_pod_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu/request",
     "query": "SELECT mean(\"value\") FROM \"cpu/request\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^mistral-executor/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-executor/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral Notifier CPU Usage",
   "type": "timeseries",
   "description": "Displays Mistral Notifier CPU usage (in millicores),  CPU limit and CPU requested for each Notifier pod",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "usage: $tag_pod_name",
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$mistral_namespace\", cluster=\"$cluster\",pod=~\"mistral-notifier.+\"}[$inter])) by (pod)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "measurement": "cpu/usage_rate",
     "query": "SELECT mean(\"value\") FROM \"cpu/usage_rate\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^mistral-notifier/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-notifier/" }
     ]
    },
    {
     "alias": "limit: $tag_pod_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu/limit",
     "query": "SELECT mean(\"value\") FROM \"cpu/limit\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^mistral-notifier/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-notifier/" }
     ]
    },
    {
     "alias": "request: $tag_pod_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu/request",
     "query": "SELECT mean(\"value\") FROM \"cpu/request\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\"='$project'  AND \"pod_name\" =~ /^mistral-notifier/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-notifier/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral Monitoring CPU Usage",
   "type": "timeseries",
   "description": "Displays Mistral Monitoring CPU usage (in millicores),  CPU limit and CPU requested for each Monitoring pod",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "usage: $tag_pod_name",
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$mistral_namespace\", cluster=\"$cluster\",pod=~\"mistral-monitoring.+\"}[$inter])) by (pod)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "measurement": "cpu/usage_rate",
     "query": "SELECT mean(\"value\") FROM \"cpu/usage_rate\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^mistral-monitoring/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-monitoring/" }
     ]
    },
    {
     "alias": "limit: $tag_pod_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu/limit",
     "query": "SELECT mean(\"value\") FROM \"cpu/limit\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\"='$project'  AND \"pod_name\" =~ /^mistral-monitoring/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-monitoring/" }
     ]
    },
    {
     "alias": "request: $tag_pod_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu/request",
     "query": "SELECT mean(\"value\") FROM \"cpu/request\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^mistral-monitoring/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-monitoring/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral MEM Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mistral Engine MEM Usage",
   "type": "timeseries",
   "description": "Displays Mistral Engine memory usage (in MiB),  memory limit and memory requested for each Engine pod",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "usage: $tag_pod_name",
     "expr": "sum(container_memory_usage_bytes{container!=\"POD\",image!=\"\",namespace=\"$mistral_namespace\", cluster=\"$cluster\",container=~\"mistral-engine\"}) by (pod)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "measurement": "memory/usage",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^mistral-engine/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-engine/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral Executor MEM Usage",
   "type": "timeseries",
   "description": "Displays Mistral Executor memory usage (in MiB),  memory limit and memory requested for each Executor pod",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "usage: $tag_pod_name",
     "expr": "sum(container_memory_usage_bytes{container!=\"POD\",image!=\"\",namespace=\"$mistral_namespace\", cluster=\"$cluster\",container=~\"mistral-executor\"}) by (pod)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "measurement": "memory/usage",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^mistral-executor/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-executor/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral API MEM Usage",
   "type": "timeseries",
   "description": "Displays Mistral API memory usage (in MiB),  memory limit and memory requested for each API pod",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "usage: $tag_pod_name",
     "expr": "sum(container_memory_usage_bytes{container!=\"POD\",image!=\"\",namespace=\"$mistral_namespace\", cluster=\"$cluster\",container=~\"mistral-api\"}) by (pod)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "measurement": "memory/usage",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^mistral-api/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-api/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral Notifier MEM Usage",
   "type": "timeseries",
   "description": "Displays Mistral Notifier memory usage (in MiB),  memory limit and memory requested for each Notifier pod",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "usage: $tag_pod_name",
     "expr": "sum(container_memory_usage_bytes{container!=\"POD\",image!=\"\",namespace=\"$mistral_namespace\", cluster=\"$cluster\",container=~\"mistral-notifier\"}) by (pod)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "measurement": "memory/usage",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\"='$project'  AND \"pod_name\" =~ /^mistral-notifier/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-notifier/" }
     ]
    }
   ]
  },
  {
   "title": "Mistral Monitoring MEM Usage",
   "type": "timeseries",
   "description": "Displays Mistral Monitoring memory usage (in MiB),  memory limit and memory requested for each Monitoring pod",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "usage: $tag_pod_name",
     "expr": "sum(container_memory_usage_bytes{container!=\"POD\",image!=\"\",namespace=\"$mistral_namespace\", cluster=\"$cluster\",container=~\"mistral-monitoring\"}) by (pod)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "measurement": "memory/usage",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" ='$project'  AND \"pod_name\" =~ /^mistral-monitoring/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^mistral-monitoring/" }
     ]
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RabbitMQ Status",
   "type": "stat",
   "description": "RabbitMQ status (Up, Down)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(topk(1, rabbitmq_status{namespace=\"$mistral_namespace\", cluster=\"$cluster\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"state\") FROM \"rabbitmq_status\" WHERE (\"namespace\" ='$project') AND time >= now() - 2m ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mistral Engine Messages Count",
   "type": "timeseries",
   "description": "Displays number of messages in Mistral engine queue",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Messages count",
     "expr": "max(topk(1, rabbitmq_queues{namespace=\"$mistral_namespace\", cluster=\"$cluster\",queue=\"_mistral_engine\"})) by (queue)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{queue}}",
     "measurement": "rabbitmq_queues",
     "query": "SELECT mean(\"messages_count\") FROM \"rabbitmq_queues\" WHERE (\"namespace\" ='$project' AND \"name\" = '_mistral_engine') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "messages_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "_mistral_engine" }
     ]
    }
   ]
  },
  {
   "title": "Mistral Executor Messages Count",
   "type": "timeseries",
   "description": "Displays number of messages in Mistral executor queue",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Messages count",
     "expr": "max(topk(1, rabbitmq_queues{namespace=\"$mistral_namespace\", cluster=\"$cluster\",queue=\"_mistral_executor\"})) by (queue)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{queue}}",
     "measurement": "rabbitmq_queues",
     "query": "SELECT mean(\"messages_count\") FROM \"rabbitmq_queues\" WHERE (\"namespace\" ='$project' AND \"name\" = '_mistral_executor') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "messages_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "_mistral_executor" }
     ]
    }
   ]
  },
  {
   "title": "Mistral Notifier Messages Count",
   "type": "timeseries",
   "description": "Displays number of messages in Mistral notifier queue",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Messages count",
     "expr": "max(topk(1, rabbitmq_queues{namespace=\"$mistral_namespace\", cluster=\"$cluster\",queue=\"_mistral_notifier\"})) by (queue)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{queue}}",
     "measurement": "rabbitmq_queues",
     "query": "SELECT mean(\"messages_count\") FROM \"rabbitmq_queues\" WHERE (\"namespace\" ='$project' AND \"name\" = '_mistral_notifier') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "messages_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "_mistral_notifier" }
     ]
    }
   ]
  }
 ]
}