{{- if eq (include "integrationTests.enabled" .) "true" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tests-config
  labels:
    app: mistral-tests
data:
  dd_images: {{ template "mistral.monitoredImages" . }}
{{ end }}