apiVersion: apps/v1
kind: Deployment
metadata:
  name: mistral-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mistral-operator
  template:
    metadata:
      labels:
        name: mistral-operator
    spec:
      serviceAccountName: mistral-operator
      containers:
        - name: mistral-operator
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_DELETE_RESOURCES
              value: 'False'
              