{{if .Values.mistralLite.includeLocalRmq }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-patcher-and-reader
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-patcher-and-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-patcher-and-reader
subjects:
  - kind: ServiceAccount
    name: rabbitmq
{{ end }}