---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mistral-operator
rules:
- apiGroups:
  - qubership.org
  resources:
  - "mistralservices"
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - events
  - services
  - endpoints
  - configmaps
  - secrets
  - pods/exec
  - pods/portforward
  - pods/attach
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
